apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: full-python-backend-postgres-password
  namespace: and
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: deepagent-aws
    kind: ClusterSecretStore
  target:
    name: app-env
    creationPolicy: Merge
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: teams-dev/and/POSTGRES_PASSWORD
